language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="meson desktop-file-utils gettext libgtk-3-dev libgee-0.8-dev libxml2-dev libjson-glib-dev libgnomekbd-dev libpwquality-dev libxml2-utils valac"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build && cd build && ninja"
 - docker pull elementary/docker:loki-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && rm -rf build && meson build && cd build && ninja"

script:
 - echo BUILDS PASSED
